import Head from "next/head";
import type { NextPage, GetStaticProps } from "next";
import { serverSideTranslations } from "next-i18next/serverSideTranslations";
import { useTranslation } from "next-i18next";
import { useState } from "react";
import Navbar from "~/components/Navbar/Navbar";
import Input from "~/components/Input/Input";
import Button from "~/components/Button/Button";
import {
  Play,
  CursorClick,
  Gift,
  Translate,
  Sun,
  Heart,
} from "@phosphor-icons/react";
import StepCard from "~/components/Cards/StepCard/StepCard";
import FeatureCard from "~/components/Cards/FeatureCard/FeatureCard";
import Footer from "~/components/Footer/Footer";

const Home: NextPage = () => {
  const { t } = useTranslation("common");

  const [email, setEmail] = useState("");
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Navbar />
        <section className="flex flex-col items-center justify-center gap-8 px-6 py-10 text-center lg:flex-row lg:items-start lg:justify-between lg:px-24 lg:text-left">
          <div className="flex flex-col gap-6 lg:mt-8 lg:gap-10">
            <div className="flex flex-col gap-4 lg:text-lg">
              <h1 className="font-montserrat text-3xl font-bold lg:text-5xl">
                <span className="bg-gradient-to-t from-neutral-950 to-neutral-950/50 bg-clip-text text-transparent dark:bg-gradient-to-b dark:from-neutral-50 dark:to-neutral-50/50">
                  {t("discover_perfect_gift_start")}
                </span>
                <span className="bg-gradient-to-t from-red-500 to-red-500/50 bg-clip-text text-transparent dark:bg-gradient-to-b">
                  {t("perfect_gift")}
                </span>
                <span className="bg-gradient-to-t from-neutral-950 to-neutral-950/50 bg-clip-text text-transparent dark:bg-gradient-to-b dark:from-neutral-50 dark:to-neutral-50/50">
                  {t("discover_perfect_gift_end")}
                </span>
                <span className="bg-gradient-to-t from-red-500 to-red-500/50 bg-clip-text text-transparent dark:bg-gradient-to-b">
                  {t("ai")}
                </span>
              </h1>
              <p className="font-lato text-neutral-800 dark:text-neutral-200">
                {t("storm_of_gift_ideas")}
              </p>
            </div>
            <div className="flex flex-col items-center gap-4 lg:flex-row">
              <div className="w-full lg:w-auto">
                <Input
                  type="email"
                  value={email}
                  onChange={(e) => setEmail(e.target.value)}
                  placeholder={t("enter_email")}
                />
              </div>
              <div>
                <Button variant="contained" size="md">
                  {t("get_early_access")}
                </Button>
              </div>
            </div>
          </div>
          <div className="flex aspect-video w-full items-center justify-center rounded border border-neutral-400 bg-neutral-200 shadow dark:border-neutral-600 dark:bg-neutral-800 dark:shadow-[0px_1px_3px_rgba(255,255,255,0.1),0px_1px_2px_-1px_rgba(255,255,255,0.1)] lg:max-w-[50%]">
            <video controls className="rounded ">
              <source
                src="https://res.cloudinary.com/dhwxnbnaj/video/upload/v1689133535/Rick_Rolled_dojqni.mp4"
                type="video/mp4"
              />
              Your browser does not support the video tag.
            </video>
          </div>
        </section>
        <Footer />
      </main>
    </>
  );
};

export const getStaticProps: GetStaticProps = async ({ locale }) => ({
  props: {
    ...(await serverSideTranslations(locale || "en", ["common"])),
  },
});

export default Home;
